// frontend/src/components/BlockQuote.tsx
import styled from "@emotion/styled";
import { ReactElement } from "react";

const Quote = styled.blockquote`
  border-left: 2px solid grey;
  padding-left: 5px;
`;

const Citation = styled.p`
  text-align: right;
`;

interface BlockQuoteProps {
  quote: string;
  citation: string;
}

const BlockQuote: React.FunctionComponent<BlockQuoteProps> = ({
  quote,
  citation,
}): ReactElement => {
  return (
    <div>
      <Quote>{quote}</Quote>
      <Citation>
        <cite>- {citation}</cite>
      </Citation>
    </div>
  );
};

export default BlockQuote;

// src/components/BlockQuote.vue
<template>
    <div>
        <blockquote class="blockquote">
            {{ quote }}
        </blockquote>
        <p class="quote-citation">
            <cite>- {{ citation }}</cite>
        </p>
    </div>
</template>

<script>
export default {
  name: "BlockQuote",
  props: [
      "quote",
      "citation"
    ],
};
</script>

<style >
.blockquote {
    border-left: 2px solid var(--v-accent-base);
    padding-left: 5px;
}

.quote-citation {
    text-align: right;
}
</style>
